#!/usr/bin/env python2
from argparse import ArgumentParser
from tadutils import *

def get_parser():
    parser = ArgumentParser(description='Create a new exit pair')
    parser.add_argument('-f', help='filename of the first room')
    parser.add_argument('-d', help='direction from inside->outside')
    parser.add_argument('-s', help='filename of the second room')
    parser.add_argument('-o', help='set "out" alias', action='store_true')

    return parser

parser = get_parser()
args = parser.parse_args()

if "__main__" == __name__:
    create_exit(
        args.f, args.d, args.s, args.o
    )
    create_exit(
        args.s, FLIPS[args.d], args.f,
    )

